accounts/urls.py
# myblog/accounts/urls.py
 
from django.urls import path
 
from . import views
 
# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'
 
urlpatterns = [
    # ex: /accounts/signup/
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    # 書籍
    path('v1/books/', views.book_list, name='book_list'),   # 一覧
]

blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('post/', views.post_list, name='post_list'),
    # path('delete/', views.data_delete, name='data_delete'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

cms/urls.py
from django.conf.urls import url
from django.urls import path
from cms import views

app_name = 'cms'
urlpatterns = [
    # 書籍
    path('', views.book_list, name='book_list'),   # 一覧
    path('add/', views.book_edit, name='book_add'),  # 登録
    path('mod/<int:book_id>/', views.book_edit, name='book_mod'),  # 修正
    path('del/<int:book_id>/', views.book_del, name='book_del'),   # 削除
    # 感想
    path('impression/<int:book_id>/', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    path('impression/add/<int:book_id>/', views.impression_edit, name='impression_add'),        # 登録
    path('impression/mod/<int:book_id>/<int:impression_id>/', views.impression_edit, name='impression_mod'),  # 修正
    path('impression/del/<int:book_id>/<int:impression_id>/', views.impression_del, name='impression_del'),   # 削除
]

mysite/urls.py
from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views
from .views import home

urlpatterns = [
    # path('', include('blog.urls')),  # http://127.0.0.1:8000/はどうするのか
    path('blog/', include('blog.urls')),
    # https://docs.djangoproject.com/ja/2.2/intro/tutorial01/
    path('polls/', include('polls.urls')),
    # https://qiita.com/kaki_k/items/6e17597804437ef170ae
    path('cms/', include('cms.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls,),
    # https://it-engineer-lab.com/archives/544
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    # https://qiita.com/moi1990sk/items/a849fca7acb29db95508
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('', home, name='home'),
]

LOGIN_URL = 'login/'
LOGIN_REDIRECT_URL = ''

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '192845778622-g61ftg21hsfh3ju9mcvevslqfnkjlj5u.apps.googleusercontent.com'  #Paste CLient Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'YnUx9PSn2rvZrwBiWdJPQ2o8' #Paste Secret Key

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Blog App with Auth | Django2 Tutorial</title>
</head>
<body>
<div class="container">
    {% block content %}
    <header>
        <p class="site-name"><a href="{% url 'home' %}">NSApps</a></p>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="logout">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:signup' %}" class="signup">Sign up</a></li>
                <li><a href="{% url 'login' %}" class="login">Login</a></li>
                {% endif %}
                <li><a href="(% url 'blogs:create' %)" class="act">Add Post</a></li>
            </ul>
        </nav>
    </header>
    <div class="content">
    {% endblock %}
    </div>
</div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>NSApps</title>
        <!-- BootstrapのCSS読み込み -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!-- <link rel="stylesheet" href="stylesheet.css">     -->
        <!-- jQuery読み込み -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- BootstrapのJS読み込み -->
        <script src="js/bootstrap.min.js"></script>
    </head>

    <body>
        {% extends 'base.html' %}
            {% block content %}
            <div style="width: 200px; height: 50px; margin: 0 0 0 auto;">
                    {% if user.is_authenticated %}
                        <p class="display-4" style="font-size: 20px; margin: 0;">Hello, {{ user.username }}</p>
                        <a class="lead" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                        <a class="lead" style="float: right;" href="{% url 'login' %}">Log in</a>
                    {% endif %}
            </div>
            <p style="float: right;"><a href="{% url 'admin:index' %}">管理画面</a></p>
        <div class="header" style="color: white; background-color: #404040;">
            <div class="row">
                <div class="header-logo col-lg-2 col-md-2 col-sm-2">NSApps</div>
                <div class="header-logo col-lg-4 col-md-2 col-sm-0"></div>
                <div class="header-list col-lg-6 col-md-8 col-sm-10">
                    <ul class="row" style="list-style: none">
                        <li class="col-lg-3 col-md-3 col-sm-3"><a href="{% url 'blog:post_list' %}">日報</a></li>
                        <li class="col-lg-3 col-md-3 col-sm-3"><a href="{% url 'cms:book_list' %}">ターゲット</a></li>
                        <li class="col-lg-3 col-md-3 col-sm-3"><a href="{% url 'polls:index' %}">アンケート</a></li>
                        <li class="col-lg-3 col-md-3 col-sm-3">LINEworks</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="main">
            <div class="copy-container">
                <h2 style="margin-bottom: 50px;">NSApps</h2>
            </div>

            <div class="contents" style="margin: 40px">
                <h3 class="section-title" style="margin-bottom: 30px;">コンテンツ</h3>
                <div class="contents-box row">
                    <div class="contents-item col-lg-3 col-md-6 col-sm-3" style="background-color: #c0c0c0;">
                        <img src="">
                        <p><a href="{% url 'blog:post_list' %}">日報</a></p>
                    </div>
                    <div class="contents-item col-lg-3 col-md-6 col-sm-3" style="background-color: #a0a0a0">
                        <img src="">
                        <p><a href="{% url 'cms:book_list' %}">ターゲット</a></p>
                    </div>
                    <div class="contents-item col-lg-3 col-md-6 col-sm-3" style="background-color: #808080;">
                        <img src="">
                        <p><a href="{% url 'polls:index' %}">アンケート</a></p>
                    </div>
                    <div class="contents-item col-lg-3 col-md-6 col-sm-3" style="background-color: #606060">
                        <img src="">
                        <p>LINEworks</p>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>